///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CurrencyData {
/*
{
  "TRY": 31.0651853959
} 
*/

  double? TRY;

  CurrencyData({
    this.TRY,
  });
  CurrencyData.fromJson(Map<String, dynamic> json) {
    TRY = json['TRY']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['TRY'] = TRY;
    return data;
  }
}

class Currency {
/*
{
  "data": {
    "TRY": 31.0651853959
  }
} 
*/

  CurrencyData? data;

  Currency({
    this.data,
  });
  Currency.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? CurrencyData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
